spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/amadeusDb
    username: amadeusUser
    password: amadeusPassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
  profiles:
    default: dev
logging:
  level:
    root: info
server:
  port: 1112

jwt:
  secret-key: "ICV6gy7CDKPHMGJxV80nDZ7Vxe0ciqyzXDHr4mTDrdTyi6fNleYAyhEZq2J29HSI5bhWnJyOBzg2bssBUKMYlC2Sr8WFUas5MAKIr2UhtZHDsrCxggQuaHpF4aGCFZ1Qc0rrDXvKLuk1Kzrfw1bQbqH6xTmg2kWQuSGuTlbTbDhyhRfu1WDs"
  expiration-time: 86400000